swagger: "2.0"
info:
  version: "1.0.0"
  title: Test api
host: localhost:4200
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /posts:
    get:
      description: Returns all posts from the system that the user has access to
      produces:
      - application/json
      responses:
        '200':
          description: A list of posts.
          schema:
            type: array
            items: {
              "type": "object"
            }
